# Generated by Django 5.1.3 on 2024-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
